for(j=0;j<61;j++)OK61[j]=1;
for(j=38;j<=61;j++)OK61[(j*STEP)%61]=0;
for(j=0;j<67;j++)OK67[j]=1;
for(j=44;j<=67;j++)OK67[(j*STEP)%67]=0;
for(j=0;j<71;j++)OK71[j]=1;
for(j=48;j<=71;j++)OK71[(j*STEP)%71]=0;
for(j=0;j<73;j++)OK73[j]=1;
for(j=50;j<=73;j++)OK73[(j*STEP)%73]=0;
for(j=0;j<79;j++)OK79[j]=1;
for(j=56;j<=79;j++)OK79[(j*STEP)%79]=0;
for(j=0;j<83;j++)OK83[j]=1;
for(j=60;j<=83;j++)OK83[(j*STEP)%83]=0;
for(j=0;j<89;j++)OK89[j]=1;
for(j=66;j<=89;j++)OK89[(j*STEP)%89]=0;
for(j=0;j<97;j++)OK97[j]=1;
for(j=74;j<=97;j++)OK97[(j*STEP)%97]=0;
for(j=0;j<101;j++)OK101[j]=1;
for(j=78;j<=101;j++)OK101[(j*STEP)%101]=0;
for(j=0;j<103;j++)OK103[j]=1;
for(j=80;j<=103;j++)OK103[(j*STEP)%103]=0;
for(j=0;j<107;j++)OK107[j]=1;
for(j=84;j<=107;j++)OK107[(j*STEP)%107]=0;
for(j=0;j<109;j++)OK109[j]=1;
for(j=86;j<=109;j++)OK109[(j*STEP)%109]=0;
for(j=0;j<113;j++)OK113[j]=1;
for(j=90;j<=113;j++)OK113[(j*STEP)%113]=0;
for(j=0;j<127;j++)OK127[j]=1;
for(j=104;j<=127;j++)OK127[(j*STEP)%127]=0;
for(j=0;j<131;j++)OK131[j]=1;
for(j=108;j<=131;j++)OK131[(j*STEP)%131]=0;
for(j=0;j<137;j++)OK137[j]=1;
for(j=114;j<=137;j++)OK137[(j*STEP)%137]=0;
for(j=0;j<139;j++)OK139[j]=1;
for(j=116;j<=139;j++)OK139[(j*STEP)%139]=0;
for(j=0;j<149;j++)OK149[j]=1;
for(j=126;j<=149;j++)OK149[(j*STEP)%149]=0;
for(j=0;j<151;j++)OK151[j]=1;
for(j=128;j<=151;j++)OK151[(j*STEP)%151]=0;
for(j=0;j<157;j++)OK157[j]=1;
for(j=134;j<=157;j++)OK157[(j*STEP)%157]=0;
for(j=0;j<163;j++)OK163[j]=1;
for(j=140;j<=163;j++)OK163[(j*STEP)%163]=0;
for(j=0;j<167;j++)OK167[j]=1;
for(j=144;j<=167;j++)OK167[(j*STEP)%167]=0;
for(j=0;j<173;j++)OK173[j]=1;
for(j=150;j<=173;j++)OK173[(j*STEP)%173]=0;
for(j=0;j<179;j++)OK179[j]=1;
for(j=156;j<=179;j++)OK179[(j*STEP)%179]=0;
for(j=0;j<181;j++)OK181[j]=1;
for(j=158;j<=181;j++)OK181[(j*STEP)%181]=0;
for(j=0;j<191;j++)OK191[j]=1;
for(j=168;j<=191;j++)OK191[(j*STEP)%191]=0;
for(j=0;j<193;j++)OK193[j]=1;
for(j=170;j<=193;j++)OK193[(j*STEP)%193]=0;
for(j=0;j<197;j++)OK197[j]=1;
for(j=174;j<=197;j++)OK197[(j*STEP)%197]=0;
for(j=0;j<199;j++)OK199[j]=1;
for(j=176;j<=199;j++)OK199[(j*STEP)%199]=0;
for(j=0;j<211;j++)OK211[j]=1;
for(j=188;j<=211;j++)OK211[(j*STEP)%211]=0;
for(j=0;j<223;j++)OK223[j]=1;
for(j=200;j<=223;j++)OK223[(j*STEP)%223]=0;
for(j=0;j<227;j++)OK227[j]=1;
for(j=204;j<=227;j++)OK227[(j*STEP)%227]=0;
for(j=0;j<229;j++)OK229[j]=1;
for(j=206;j<=229;j++)OK229[(j*STEP)%229]=0;
for(j=0;j<233;j++)OK233[j]=1;
for(j=210;j<=233;j++)OK233[(j*STEP)%233]=0;
for(j=0;j<239;j++)OK239[j]=1;
for(j=216;j<=239;j++)OK239[(j*STEP)%239]=0;
for(j=0;j<241;j++)OK241[j]=1;
for(j=218;j<=241;j++)OK241[(j*STEP)%241]=0;
for(j=0;j<251;j++)OK251[j]=1;
for(j=228;j<=251;j++)OK251[(j*STEP)%251]=0;
for(j=0;j<257;j++)OK257[j]=1;
for(j=234;j<=257;j++)OK257[(j*STEP)%257]=0;
for(j=0;j<263;j++)OK263[j]=1;
for(j=240;j<=263;j++)OK263[(j*STEP)%263]=0;
for(j=0;j<269;j++)OK269[j]=1;
for(j=246;j<=269;j++)OK269[(j*STEP)%269]=0;
for(j=0;j<271;j++)OK271[j]=1;
for(j=248;j<=271;j++)OK271[(j*STEP)%271]=0;
for(j=0;j<277;j++)OK277[j]=1;
for(j=254;j<=277;j++)OK277[(j*STEP)%277]=0;
for(j=0;j<281;j++)OK281[j]=1;
for(j=258;j<=281;j++)OK281[(j*STEP)%281]=0;
for(j=0;j<283;j++)OK283[j]=1;
for(j=260;j<=283;j++)OK283[(j*STEP)%283]=0;
for(j=0;j<293;j++)OK293[j]=1;
for(j=270;j<=293;j++)OK293[(j*STEP)%293]=0;
for(j=0;j<307;j++)OK307[j]=1;
for(j=284;j<=307;j++)OK307[(j*STEP)%307]=0;
for(j=0;j<311;j++)OK311[j]=1;
for(j=288;j<=311;j++)OK311[(j*STEP)%311]=0;
for(j=0;j<313;j++)OK313[j]=1;
for(j=290;j<=313;j++)OK313[(j*STEP)%313]=0;
for(j=0;j<317;j++)OK317[j]=1;
for(j=294;j<=317;j++)OK317[(j*STEP)%317]=0;
for(j=0;j<331;j++)OK331[j]=1;
for(j=308;j<=331;j++)OK331[(j*STEP)%331]=0;
for(j=0;j<337;j++)OK337[j]=1;
for(j=314;j<=337;j++)OK337[(j*STEP)%337]=0;
for(j=0;j<347;j++)OK347[j]=1;
for(j=324;j<=347;j++)OK347[(j*STEP)%347]=0;
for(j=0;j<349;j++)OK349[j]=1;
for(j=326;j<=349;j++)OK349[(j*STEP)%349]=0;
for(j=0;j<353;j++)OK353[j]=1;
for(j=330;j<=353;j++)OK353[(j*STEP)%353]=0;
for(j=0;j<359;j++)OK359[j]=1;
for(j=336;j<=359;j++)OK359[(j*STEP)%359]=0;
for(j=0;j<367;j++)OK367[j]=1;
for(j=344;j<=367;j++)OK367[(j*STEP)%367]=0;
for(j=0;j<373;j++)OK373[j]=1;
for(j=350;j<=373;j++)OK373[(j*STEP)%373]=0;
for(j=0;j<379;j++)OK379[j]=1;
for(j=356;j<=379;j++)OK379[(j*STEP)%379]=0;
for(j=0;j<383;j++)OK383[j]=1;
for(j=360;j<=383;j++)OK383[(j*STEP)%383]=0;
for(j=0;j<389;j++)OK389[j]=1;
for(j=366;j<=389;j++)OK389[(j*STEP)%389]=0;
for(j=0;j<397;j++)OK397[j]=1;
for(j=374;j<=397;j++)OK397[(j*STEP)%397]=0;
for(j=0;j<401;j++)OK401[j]=1;
for(j=378;j<=401;j++)OK401[(j*STEP)%401]=0;
for(j=0;j<409;j++)OK409[j]=1;
for(j=386;j<=409;j++)OK409[(j*STEP)%409]=0;
for(j=0;j<419;j++)OK419[j]=1;
for(j=396;j<=419;j++)OK419[(j*STEP)%419]=0;
for(j=0;j<421;j++)OK421[j]=1;
for(j=398;j<=421;j++)OK421[(j*STEP)%421]=0;
for(j=0;j<431;j++)OK431[j]=1;
for(j=408;j<=431;j++)OK431[(j*STEP)%431]=0;
for(j=0;j<433;j++)OK433[j]=1;
for(j=410;j<=433;j++)OK433[(j*STEP)%433]=0;
for(j=0;j<439;j++)OK439[j]=1;
for(j=416;j<=439;j++)OK439[(j*STEP)%439]=0;
for(j=0;j<443;j++)OK443[j]=1;
for(j=420;j<=443;j++)OK443[(j*STEP)%443]=0;
for(j=0;j<449;j++)OK449[j]=1;
for(j=426;j<=449;j++)OK449[(j*STEP)%449]=0;
for(j=0;j<457;j++)OK457[j]=1;
for(j=434;j<=457;j++)OK457[(j*STEP)%457]=0;
for(j=0;j<461;j++)OK461[j]=1;
for(j=438;j<=461;j++)OK461[(j*STEP)%461]=0;
for(j=0;j<463;j++)OK463[j]=1;
for(j=440;j<=463;j++)OK463[(j*STEP)%463]=0;
for(j=0;j<467;j++)OK467[j]=1;
for(j=444;j<=467;j++)OK467[(j*STEP)%467]=0;
for(j=0;j<479;j++)OK479[j]=1;
for(j=456;j<=479;j++)OK479[(j*STEP)%479]=0;
for(j=0;j<487;j++)OK487[j]=1;
for(j=464;j<=487;j++)OK487[(j*STEP)%487]=0;
for(j=0;j<491;j++)OK491[j]=1;
for(j=468;j<=491;j++)OK491[(j*STEP)%491]=0;
for(j=0;j<499;j++)OK499[j]=1;
for(j=476;j<=499;j++)OK499[(j*STEP)%499]=0;
for(j=0;j<503;j++)OK503[j]=1;
for(j=480;j<=503;j++)OK503[(j*STEP)%503]=0;
for(j=0;j<509;j++)OK509[j]=1;
for(j=486;j<=509;j++)OK509[(j*STEP)%509]=0;
for(j=0;j<521;j++)OK521[j]=1;
for(j=498;j<=521;j++)OK521[(j*STEP)%521]=0;
for(j=0;j<523;j++)OK523[j]=1;
for(j=500;j<=523;j++)OK523[(j*STEP)%523]=0;
for(j=0;j<541;j++)OK541[j]=1;
for(j=518;j<=541;j++)OK541[(j*STEP)%541]=0;
for(j=0;j<61;j++)OKOK61[j]=0;
for(j=0;j<61;j++)
for(jj=0;jj<64;jj++)
OKOK61[j]|=(((long long)OK61[(j+(jj+SHIFT)*MOD)%61])<<jj);
for(j=0;j<67;j++)OKOK67[j]=0;
for(j=0;j<67;j++)
for(jj=0;jj<64;jj++)
OKOK67[j]|=(((long long)OK67[(j+(jj+SHIFT)*MOD)%67])<<jj);
for(j=0;j<71;j++)OKOK71[j]=0;
for(j=0;j<71;j++)
for(jj=0;jj<64;jj++)
OKOK71[j]|=(((long long)OK71[(j+(jj+SHIFT)*MOD)%71])<<jj);
for(j=0;j<73;j++)OKOK73[j]=0;
for(j=0;j<73;j++)
for(jj=0;jj<64;jj++)
OKOK73[j]|=(((long long)OK73[(j+(jj+SHIFT)*MOD)%73])<<jj);
for(j=0;j<79;j++)OKOK79[j]=0;
for(j=0;j<79;j++)
for(jj=0;jj<64;jj++)
OKOK79[j]|=(((long long)OK79[(j+(jj+SHIFT)*MOD)%79])<<jj);
for(j=0;j<83;j++)OKOK83[j]=0;
for(j=0;j<83;j++)
for(jj=0;jj<64;jj++)
OKOK83[j]|=(((long long)OK83[(j+(jj+SHIFT)*MOD)%83])<<jj);
for(j=0;j<89;j++)OKOK89[j]=0;
for(j=0;j<89;j++)
for(jj=0;jj<64;jj++)
OKOK89[j]|=(((long long)OK89[(j+(jj+SHIFT)*MOD)%89])<<jj);
for(j=0;j<97;j++)OKOK97[j]=0;
for(j=0;j<97;j++)
for(jj=0;jj<64;jj++)
OKOK97[j]|=(((long long)OK97[(j+(jj+SHIFT)*MOD)%97])<<jj);
for(j=0;j<101;j++)OKOK101[j]=0;
for(j=0;j<101;j++)
for(jj=0;jj<64;jj++)
OKOK101[j]|=(((long long)OK101[(j+(jj+SHIFT)*MOD)%101])<<jj);
for(j=0;j<103;j++)OKOK103[j]=0;
for(j=0;j<103;j++)
for(jj=0;jj<64;jj++)
OKOK103[j]|=(((long long)OK103[(j+(jj+SHIFT)*MOD)%103])<<jj);
for(j=0;j<107;j++)OKOK107[j]=0;
for(j=0;j<107;j++)
for(jj=0;jj<64;jj++)
OKOK107[j]|=(((long long)OK107[(j+(jj+SHIFT)*MOD)%107])<<jj);
for(j=0;j<109;j++)OKOK109[j]=0;
for(j=0;j<109;j++)
for(jj=0;jj<64;jj++)
OKOK109[j]|=(((long long)OK109[(j+(jj+SHIFT)*MOD)%109])<<jj);
for(j=0;j<113;j++)OKOK113[j]=0;
for(j=0;j<113;j++)
for(jj=0;jj<64;jj++)
OKOK113[j]|=(((long long)OK113[(j+(jj+SHIFT)*MOD)%113])<<jj);
for(j=0;j<127;j++)OKOK127[j]=0;
for(j=0;j<127;j++)
for(jj=0;jj<64;jj++)
OKOK127[j]|=(((long long)OK127[(j+(jj+SHIFT)*MOD)%127])<<jj);
for(j=0;j<131;j++)OKOK131[j]=0;
for(j=0;j<131;j++)
for(jj=0;jj<64;jj++)
OKOK131[j]|=(((long long)OK131[(j+(jj+SHIFT)*MOD)%131])<<jj);
for(j=0;j<137;j++)OKOK137[j]=0;
for(j=0;j<137;j++)
for(jj=0;jj<64;jj++)
OKOK137[j]|=(((long long)OK137[(j+(jj+SHIFT)*MOD)%137])<<jj);
for(j=0;j<139;j++)OKOK139[j]=0;
for(j=0;j<139;j++)
for(jj=0;jj<64;jj++)
OKOK139[j]|=(((long long)OK139[(j+(jj+SHIFT)*MOD)%139])<<jj);
for(j=0;j<149;j++)OKOK149[j]=0;
for(j=0;j<149;j++)
for(jj=0;jj<64;jj++)
OKOK149[j]|=(((long long)OK149[(j+(jj+SHIFT)*MOD)%149])<<jj);
for(j=0;j<151;j++)OKOK151[j]=0;
for(j=0;j<151;j++)
for(jj=0;jj<64;jj++)
OKOK151[j]|=(((long long)OK151[(j+(jj+SHIFT)*MOD)%151])<<jj);
for(j=0;j<157;j++)OKOK157[j]=0;
for(j=0;j<157;j++)
for(jj=0;jj<64;jj++)
OKOK157[j]|=(((long long)OK157[(j+(jj+SHIFT)*MOD)%157])<<jj);
for(j=0;j<163;j++)OKOK163[j]=0;
for(j=0;j<163;j++)
for(jj=0;jj<64;jj++)
OKOK163[j]|=(((long long)OK163[(j+(jj+SHIFT)*MOD)%163])<<jj);
for(j=0;j<167;j++)OKOK167[j]=0;
for(j=0;j<167;j++)
for(jj=0;jj<64;jj++)
OKOK167[j]|=(((long long)OK167[(j+(jj+SHIFT)*MOD)%167])<<jj);
for(j=0;j<173;j++)OKOK173[j]=0;
for(j=0;j<173;j++)
for(jj=0;jj<64;jj++)
OKOK173[j]|=(((long long)OK173[(j+(jj+SHIFT)*MOD)%173])<<jj);
for(j=0;j<179;j++)OKOK179[j]=0;
for(j=0;j<179;j++)
for(jj=0;jj<64;jj++)
OKOK179[j]|=(((long long)OK179[(j+(jj+SHIFT)*MOD)%179])<<jj);
for(j=0;j<181;j++)OKOK181[j]=0;
for(j=0;j<181;j++)
for(jj=0;jj<64;jj++)
OKOK181[j]|=(((long long)OK181[(j+(jj+SHIFT)*MOD)%181])<<jj);
for(j=0;j<191;j++)OKOK191[j]=0;
for(j=0;j<191;j++)
for(jj=0;jj<64;jj++)
OKOK191[j]|=(((long long)OK191[(j+(jj+SHIFT)*MOD)%191])<<jj);
for(j=0;j<193;j++)OKOK193[j]=0;
for(j=0;j<193;j++)
for(jj=0;jj<64;jj++)
OKOK193[j]|=(((long long)OK193[(j+(jj+SHIFT)*MOD)%193])<<jj);
for(j=0;j<197;j++)OKOK197[j]=0;
for(j=0;j<197;j++)
for(jj=0;jj<64;jj++)
OKOK197[j]|=(((long long)OK197[(j+(jj+SHIFT)*MOD)%197])<<jj);
for(j=0;j<199;j++)OKOK199[j]=0;
for(j=0;j<199;j++)
for(jj=0;jj<64;jj++)
OKOK199[j]|=(((long long)OK199[(j+(jj+SHIFT)*MOD)%199])<<jj);
for(j=0;j<211;j++)OKOK211[j]=0;
for(j=0;j<211;j++)
for(jj=0;jj<64;jj++)
OKOK211[j]|=(((long long)OK211[(j+(jj+SHIFT)*MOD)%211])<<jj);
for(j=0;j<223;j++)OKOK223[j]=0;
for(j=0;j<223;j++)
for(jj=0;jj<64;jj++)
OKOK223[j]|=(((long long)OK223[(j+(jj+SHIFT)*MOD)%223])<<jj);
for(j=0;j<227;j++)OKOK227[j]=0;
for(j=0;j<227;j++)
for(jj=0;jj<64;jj++)
OKOK227[j]|=(((long long)OK227[(j+(jj+SHIFT)*MOD)%227])<<jj);
for(j=0;j<229;j++)OKOK229[j]=0;
for(j=0;j<229;j++)
for(jj=0;jj<64;jj++)
OKOK229[j]|=(((long long)OK229[(j+(jj+SHIFT)*MOD)%229])<<jj);
for(j=0;j<233;j++)OKOK233[j]=0;
for(j=0;j<233;j++)
for(jj=0;jj<64;jj++)
OKOK233[j]|=(((long long)OK233[(j+(jj+SHIFT)*MOD)%233])<<jj);
for(j=0;j<239;j++)OKOK239[j]=0;
for(j=0;j<239;j++)
for(jj=0;jj<64;jj++)
OKOK239[j]|=(((long long)OK239[(j+(jj+SHIFT)*MOD)%239])<<jj);
for(j=0;j<241;j++)OKOK241[j]=0;
for(j=0;j<241;j++)
for(jj=0;jj<64;jj++)
OKOK241[j]|=(((long long)OK241[(j+(jj+SHIFT)*MOD)%241])<<jj);
for(j=0;j<251;j++)OKOK251[j]=0;
for(j=0;j<251;j++)
for(jj=0;jj<64;jj++)
OKOK251[j]|=(((long long)OK251[(j+(jj+SHIFT)*MOD)%251])<<jj);
for(j=0;j<257;j++)OKOK257[j]=0;
for(j=0;j<257;j++)
for(jj=0;jj<64;jj++)
OKOK257[j]|=(((long long)OK257[(j+(jj+SHIFT)*MOD)%257])<<jj);
for(j=0;j<263;j++)OKOK263[j]=0;
for(j=0;j<263;j++)
for(jj=0;jj<64;jj++)
OKOK263[j]|=(((long long)OK263[(j+(jj+SHIFT)*MOD)%263])<<jj);
for(j=0;j<269;j++)OKOK269[j]=0;
for(j=0;j<269;j++)
for(jj=0;jj<64;jj++)
OKOK269[j]|=(((long long)OK269[(j+(jj+SHIFT)*MOD)%269])<<jj);
for(j=0;j<271;j++)OKOK271[j]=0;
for(j=0;j<271;j++)
for(jj=0;jj<64;jj++)
OKOK271[j]|=(((long long)OK271[(j+(jj+SHIFT)*MOD)%271])<<jj);
for(j=0;j<277;j++)OKOK277[j]=0;
for(j=0;j<277;j++)
for(jj=0;jj<64;jj++)
OKOK277[j]|=(((long long)OK277[(j+(jj+SHIFT)*MOD)%277])<<jj);
for(j=0;j<281;j++)OKOK281[j]=0;
for(j=0;j<281;j++)
for(jj=0;jj<64;jj++)
OKOK281[j]|=(((long long)OK281[(j+(jj+SHIFT)*MOD)%281])<<jj);
for(j=0;j<283;j++)OKOK283[j]=0;
for(j=0;j<283;j++)
for(jj=0;jj<64;jj++)
OKOK283[j]|=(((long long)OK283[(j+(jj+SHIFT)*MOD)%283])<<jj);
for(j=0;j<293;j++)OKOK293[j]=0;
for(j=0;j<293;j++)
for(jj=0;jj<64;jj++)
OKOK293[j]|=(((long long)OK293[(j+(jj+SHIFT)*MOD)%293])<<jj);
for(j=0;j<307;j++)OKOK307[j]=0;
for(j=0;j<307;j++)
for(jj=0;jj<64;jj++)
OKOK307[j]|=(((long long)OK307[(j+(jj+SHIFT)*MOD)%307])<<jj);
for(j=0;j<311;j++)OKOK311[j]=0;
for(j=0;j<311;j++)
for(jj=0;jj<64;jj++)
OKOK311[j]|=(((long long)OK311[(j+(jj+SHIFT)*MOD)%311])<<jj);
for(j=0;j<313;j++)OKOK313[j]=0;
for(j=0;j<313;j++)
for(jj=0;jj<64;jj++)
OKOK313[j]|=(((long long)OK313[(j+(jj+SHIFT)*MOD)%313])<<jj);
for(j=0;j<317;j++)OKOK317[j]=0;
for(j=0;j<317;j++)
for(jj=0;jj<64;jj++)
OKOK317[j]|=(((long long)OK317[(j+(jj+SHIFT)*MOD)%317])<<jj);
for(j=0;j<331;j++)OKOK331[j]=0;
for(j=0;j<331;j++)
for(jj=0;jj<64;jj++)
OKOK331[j]|=(((long long)OK331[(j+(jj+SHIFT)*MOD)%331])<<jj);
